// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
. . . . . . . . . . . . . . . . 
. . . . 6 6 6 6 6 6 6 6 . . . . 
. . . 6 9 6 6 6 6 6 6 c 6 . . . 
. . 6 c 9 6 6 6 6 6 6 c c 6 . . 
. 6 c c 9 9 9 9 9 9 6 c c 9 6 d 
. 6 c 6 8 8 8 8 8 8 8 b c 9 6 6 
. 6 6 8 b b 8 b b b 8 8 b 9 6 6 
. 6 8 b b b 8 b b b b 8 6 6 6 6 
. 8 8 6 6 6 8 6 6 6 6 6 8 6 6 6 
. 8 8 8 8 8 8 f 8 8 8 f 8 6 d d 
. 8 8 8 8 8 8 f 8 8 f 8 8 8 6 d 
. 8 8 8 8 8 8 f f f 8 8 8 8 8 8 
. 8 f f f f 8 8 8 8 f f f 8 8 8 
. . f f f f f 8 8 f f f f f 8 . 
. . . f f f . . . . f f f f . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":return img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image3":return img`
. . . . . . f f f f 4 4 f . . . 
. . . . f f b f 5 4 5 5 4 f . . 
. . . f b 3 3 e 4 5 5 5 5 f . . 
. . f b 3 3 3 3 e 4 4 4 e f . . 
. . f 3 3 3 3 3 3 3 3 3 3 f . . 
. . f 3 3 3 3 e b 3 e e 3 3 f . 
. . f 3 3 3 3 f f e e e 3 3 f . 
. . f b b b b f b f e e e 3 f . 
. . f b b b b e 1 f 4 4 e f . . 
. f f b b b b f 4 4 4 4 f . . . 
. f b b b b f f f e e e f . . . 
. . f b b f 4 4 e d d d f . . . 
. . . f f e 4 4 e d d d f . . . 
. . . . f b e e b d b d b f . . 
. . . . f f d 1 d 1 d 1 f f . . 
. . . . . . f f b b f f . . . . 
`;
            case "image4":return img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image5":return img`
. . . . . . f f f f 4 4 f . . . 
. . . . f f b f 5 4 5 5 4 f . . 
. . . f b 3 3 e 4 5 5 5 5 f . . 
. . f b 3 3 3 3 e 4 4 4 e f . . 
. . f 3 3 3 3 3 3 3 3 3 3 f . . 
. . f 3 3 3 3 e b 3 e e 3 3 f . 
. . f 3 3 3 3 f f e e e 3 3 f . 
. . f b b b b f b f e e e 3 f . 
. . f b b b b e 1 f 4 4 e f . . 
. f f b b b b f 4 4 4 4 f . . . 
. f b b b b f f f e e e f . . . 
. . f b b f 4 4 e d d d f . . . 
. . . f f e 4 4 e d d d f . . . 
. . . . f b e e b d b d b f . . 
. . . . f f d 1 d 1 d 1 f f . . 
. . . . . . f f b b f f . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
